name: network_info_plus_windows
description: Windows implementation of the network_info_plus plugin
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  network_info_plus_platform_interface: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.4 <3.0.0"

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: NetworkInfoPlusWindowsPlugin
