name: device_info_plus_web
description: An implementation for the web platform of the Flutter `device_info_plus` plugin.
version: 5.0.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      web:
        pluginClass: DeviceInfoPlusPlugin
        fileName: device_info_plus_web.dart

dependencies:
  device_info_plus_platform_interface: ^5.0.0
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ">=1.0.4 <3.0.0"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
