name: device_info_plus_linux
description: Linux implementation of the device_info_plus plugin
version: 5.0.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  device_info_plus_platform_interface: ^5.0.0
  file: ^6.0.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.4 <3.0.0"

flutter:
  plugin:
    implements: device_info_plus
    platforms:
      linux:
        dartPluginClass: DeviceInfoLinux
