name: android_alarm_manager_plus
description: Flutter plugin for accessing the Android AlarmManager service, and
  running Dart code in the background when alarms fire.
version: 2.0.7+1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/android_alarm_manager_plus

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.4 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.androidalarmmanager
        pluginClass: AndroidAlarmManagerPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
