# Build Battery Plus Example
name: battery_plus

on:
  pull_request:
    paths:
      - "packages/battery_plus/**"
      - ".github/workflows/battery_plus.yaml"

env:
  PLUGIN_SCOPE: "*battery_plus*"
  PLUGIN_EXAMPLE_SCOPE: "*battery_plus_example*"

jobs:
#  android:
#    runs-on: ubuntu-latest
#    timeout-minutes: 30
#    steps:
#      - name: "Checkout repository"
#        uses: actions/checkout@v2
#      - name: "Install Flutter"
#        run: ./.github/workflows/scripts/install-flutter.sh stable
#      - name: "Install Tools"
#        run: ./.github/workflows/scripts/install-tools.sh
#      - name: "Build Example"
#        run: ./.github/workflows/scripts/build-examples.sh android
#
#  ios:
#    runs-on: macos-latest
#    timeout-minutes: 30
#    steps:
#      - name: "Checkout repository"
#        uses: actions/checkout@v2
#      - name: "Install Flutter"
#        run: ./.github/workflows/scripts/install-flutter.sh stable
#      - name: "Install Tools"
#        run: ./.github/workflows/scripts/install-tools.sh
#      - name: "Build Example"
#        run: ./.github/workflows/scripts/build-examples.sh ios

  macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh macos

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh linux

  windows:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh windows

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh web
