# Build Connectivity Info Plus Example
name: connectivity_plus

on:
  pull_request:
    paths:
      - "packages/connectivity_plus/**"
      - ".github/workflows/connectivity_plus.yaml"

env:
  PLUGIN_SCOPE: "*connectivity_plus*"
  PLUGIN_EXAMPLE_SCOPE: "*connectivity_plus_example*"

jobs:
#  android:
#    runs-on: ubuntu-latest
#    timeout-minutes: 30
#    steps:
#      - name: "Checkout repository"
#        uses: actions/checkout@v2
#      - name: "Install Flutter"
#        run: ./.github/workflows/scripts/install-flutter.sh stable
#      - name: "Install Tools"
#        run: ./.github/workflows/scripts/install-tools.sh
#      - name: "Build Example"
#        run: ./.github/workflows/scripts/build-examples.sh android ./lib/main.dart
#
#  ios:
#    runs-on: macos-latest
#    timeout-minutes: 30
#    steps:
#      - name: "Checkout repository"
#        uses: actions/checkout@v2
#      - name: "Install Flutter"
#        run: ./.github/workflows/scripts/install-flutter.sh stable
#      - name: "Install Tools"
#        run: ./.github/workflows/scripts/install-tools.sh
#      - name: "Build Example"
#        run: ./.github/workflows/scripts/build-examples.sh ios ./lib/main.dart
